### ISSUE TITLE
Cannot install app from app store.

### ISSUE THREAD

**Issue by gremlin007** [ginkage/wearmouse#27]
I cannot install the app from the app store from a desktop, from the watch or from the phone. I'm on the GW6 Classic, Canada region

**Comment by parkerlreed** [comment]
Same here

```
Samsung Galaxy Watch4 Classic
Does not work on your device
```

**Comment by parkerlreed** [comment]
Currently cannot find any apk releases for this. Play Store downloaders refuse to grab it and there are no releases on this GitHub.

**Comment by ginkage** [comment]
Yes, I'm afraid Google has pulled it from the Play Store due to some minor issues with the UI (nobody complained about those, but that's Google for you).
I'll get to fixing those when I have some free time, but I'm afraid I'm quite swamped with some other projects (as well as my day-time job) at the moment.
In the meantime I'll uploaded some APK release soon.

**Comment by gremlin007** [comment]
Thanks! I've been trying to compile the Git into an APK but it's not easy at all and I've pretty much given up. I'll wait for the APK when you get a chance, really appreciate it.

**Comment by Faldirdk** [comment]
Merry Christmas! 🎄🎁
Hoping to get the APK as soon as you get the free time 😁
Have used your app so much in the past! 😁

**Comment by ginkage** [comment]
Sorry for the wait, I've published the APKs. Haven't tested them tbh, so please report if there are any issues.

**Comment by Faldirdk** [comment]
Just tried your .apks 😁
My phone won't open the app, says the the app has an error unfortunately 😵‍💫

Tested it on my Samsung S22 Ultra ✌️

**Comment by ginkage** [comment]
I mean, duh, these are for the watch, not the phone.

**Comment by Faldirdk** [comment]
Ah ofc 😅, my mistake! 😜
I'll give it a test 😉👌

**Comment by Faldirdk** [comment]
Just tried it out on my galaxy watch 4, works like a charm!

Thx Ginkage! 😁👌

**Comment by ginkage** [comment]
Cool!
In the meantime, I've uploaded a new version to Play Store for review, so there's still a slim chance they'll return it for general availability. Fingers crossed!

**Comment by ginkage** [comment]
...aand, already rejected, for even sillier reasons this time. Oh well.

**Comment by Faldirdk** [comment]
What? Really? What could possibly be the reason? 😵‍💫

... My last app just got rejected just because the API lvl didn't target lvl 33 🙄...

But i'm happy you made the .apk available m8!
It's great for showcasing my own apps when i need a mouse on the go 😁👌

**Comment by ginkage** [comment]
Well... You know that bottom drawer in the mouse mode, the one that allows you to click&hold? Apparently, it's the wrong color (has to be black, because everybody loves black pop-up menu on black background, not confusing at all), it's not being scrolled with rotary controls (because that's reserved for mouse wheel), and it doesn't show a scroll bar (I mean, who cares?).
Best part: that drawer is a Google's own widget, `androidx.wear.widget.drawer.WearableActionDrawerView`, so some of those issues I can't even address without e.g. forking the whole Wear support library.
Also, they don't like that the corners of the "R" button on that screen are slightly cut off (how else am I going to make it that large?)...
So yeah, just random nit-picking on their part, for hardly any reason at all.

**Comment by gremlin007** [comment]
I got it to work on my watch, thanks a lot! The keyboard control doesn't work for me though. Typing things doesn't pop The words onto the connected device. I'm not sure if I'm using it wrong or it just doesn't work. Either way, thanks again!

**Comment by ginkage** [comment]
Thanks for the feedback!
A couple details would help: for example, which keyboard you're using, and on which device.
So far, I'm aware of an issue with GBoard simply showing a black screen on Samsung devices, described here: https://www.reddit.com/r/GalaxyWatch/comments/15v0f1d/gboard_doesnt_work_on_gw6_anyone_else/
The other issue is, sometimes the keyboard is implemented as a separate app (putting WearMouse in the background), unlike the way it was implemented in Wear OS 2 (that used to be a system app overlay). The workaround for that one is to enable the "Stay connected in the background" option in the settings (you can access those after connecting to your device). Please try that and tell me if that worked for you,

**Comment by gremlin007** [comment]
Thanks a lot of the support! I'm on GW6 with Samsung keyboard and the "stay connected in the background" made it work for me. It was kicking me out to the device selection screen each time before that. Cheers!

**Comment by ginkage** [comment]
Still fighting with Play Store. A few months ago they were rejecting updates because it was marked as standalone, but requires pairing with a device. Now they've rejected it because it's not marked as standalone, and installing it on the phone doesn't work. *facepalm*

**Comment by ginkage** [comment]
A-and, it's back. I'll upload the new APKs and update the source code a bit later, but you should be now able to download it from Play Store again.
